import { colors } from "@mui/material";

export const {
  common: { white, black },
  brown,
  lime,
  lightGreen,
  green,
  teal,
  yellow,
  amber,
  orange,
  deepOrange,
  pink,
  red,
  purple,
  deepPurple,
  indigo,
  blue,
  lightBlue,
  cyan,
  blueGrey,
  grey,
} = colors;

export const DEFAULT_COLORS = [
  black,
  brown[500],
  teal[500],
  green[500],
  lightGreen[500],
  lime[500],
  yellow[500],
  amber[500],
  orange[500],
  deepOrange[500],
  red[500],
  pink[500],
  purple[500],
  deepPurple[500],
  indigo[500],
  blue[500],
  lightBlue[500],
  cyan[500],
  blueGrey[500],
  grey[500],
  // white,
];

export const DEFAULT_COLOR_ENTRIES = [
  ["black", black],
  ["brown", brown[500]],
  ["teal", teal[500]],
  ["green", green[500]],
  ["light green", lightGreen[500]],
  ["lime", lime[500]],
  ["yellow", yellow[500]],
  ["amber", amber[500]],
  ["orange", orange[500]],
  ["deep orange", deepOrange[500]],
  ["red", red[500]],
  ["pink", pink[500]],
  ["purple", purple[500]],
  ["deep purple", deepPurple[500]],
  ["indigo", indigo[500]],
  ["blue", blue[500]],
  ["light blue", lightBlue[500]],
  ["cyan", cyan[500]],
  ["blue grey", blueGrey[500]],
  ["grey", grey[500]],
];

export default colors;
